version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitnet
  backend:
    image: python-backend:latest
    container_name: 'python-backend'
    ports:
        - 8888:8888
    networks:
        - rabbitnet

networks:
  rabbitnet:
    driver: bridge