version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - ${AMQP_PORT:-5672}:5672
      - ${AMQP_WEBPORT:-15672}:15672
    volumes:
      - ${AMQP_VOLUME_DATA:-./rabbitmq/data}:/var/lib/rabbitmq
      - ${AMQP_VOLUME_LOG:-./rabbitmq/log}:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 45s
      retries: 4
    networks:
      - rabbitnet
  backend:
    build: ./backend
    image: python-backend:latest
    container_name: 'python-backend'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_HOST: ${AMQP_HOST:-rabbitmq}
      AMQP_PORT: ${AMQP_PORT:-5672}
      AMQP_USER: ${AMQP_USER:?}
      AMQP_PASSWORD: ${AMQP_PASSWORD:?}
    ports:
      - ${BACKEND_PORT:-8888}:8888
    networks:
      - rabbitnet
  servicedb:
    build: ./servicedb
    image: python-servicedb:latest
    container_name: 'python-servicedb'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_HOST: ${AMQP_HOST:-rabbitmq}
      AMQP_PORT: ${AMQP_PORT:-5672}
      AMQP_USER: ${AMQP_USER:?}
      AMQP_PASSWORD: ${AMQP_PASSWORD:?}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_NAME: ${DB_NAME:?}
    ports:
      - ${SERVICEDB_PORT:-8883}:8000
    networks:
      - rabbitnet
      - postgres
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-regmandb}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  rabbitnet:
    driver: bridge
  postgres:
    driver: bridge