version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - ${AMQP_PORT:-5672}:5672
      - ${AMQP_WEBPORT:-15672}:15672
    volumes:
      - ${AMQP_VOLUME_DATA:-./rabbitmq/data}:/var/lib/rabbitmq
      - ${AMQP_VOLUME_LOG:-./rabbitmq/log}:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 45s
      retries: 4
    networks:
      - rabbitnet
  backend:
    build: ./backend
    image: python-backend:latest
    container_name: 'python-backend'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_HOST: ${AMQP_HOST:-rabbitmq}
      AMQP_PORT: ${AMQP_PORT:-5672}
      AMQP_USER: ${AMQP_USER:?}
      AMQP_PASSWORD: ${AMQP_PASSWORD:?}
    ports:
      - ${BACKEND_PORT:-8888}:8888
    networks:
      - rabbitnet
  servicedb:
    build: ./servicedb
    image: servicedb:latest
    container_name: 'python-servicedb'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_HOST: ${AMQP_HOST:-rabbitmq}
      AMQP_PORT: ${AMQP_PORT:-5672}
      AMQP_USER: ${AMQP_USER:?}
      AMQP_PASSWORD: ${AMQP_PASSWORD:?}
    ports:
      - ${SERVICEDB_PORT:-8883}:8883
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge